name: Sync to Account B Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ secrets.TARGET_REPO_PAT }}
        fetch-depth: 0
        
    - name: Configure Git
      env:
        TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
      run: |
        git config --global user.name "ahadalichowdhury"
        git config --global user.email "smahadalichowdhury@gmail.com"
        echo "https://ahadalichowdhury:${{ secrets.TARGET_REPO_PAT }}@github.com" > ~/.git-credentials
        git config --global credential.helper store

    - name: Push to target repository (excluding .github)
      env:
        TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
      run: |
        # Create .gitignore if it doesn't exist
        echo ".github/" >> .gitignore
        git add .gitignore
        git commit -m "Update .gitignore to exclude .github directory" || true
        
        # Add and push to target
        git remote add target-repo "https://ahadalichowdhury:${{ secrets.TARGET_REPO_PAT }}@github.com/ahadalichowdhury/testing-repo-A.git"
        git fetch target-repo
        git push -u target-repo main:main --force
